package com.codingtext.codebankservice.entity;

public enum Algorithm {
    GRAPH,GREEDY,HEAP,HASH,STACK,ARITHMETIC, IMPLEMENTATION, COMBINATORICS, GEOMETRY, DP, TOPOLOGICAL_SORT, REGEX, NUMBER_THEORY, BIPARTITE_MATCHING, BRUTEFORCE, DATA_STRUCTURES, MATH

}
